# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 20:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='noticia')),
                ('imagen_red1', image_cropping.fields.ImageRatioField('imagen', '640x383', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='imagen red1')),
                ('imagen_red2', image_cropping.fields.ImageRatioField('imagen', '320x182', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='imagen red2')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=9999999)),
                ('fechap', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('estado_noticia_email', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
        migrations.CreateModel(
            name='TagsNoticia',
            fields=[
                ('id_tags', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tags_noticia',
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=models.ManyToManyField(to='appeea.TagsNoticia'),
        ),
    ]
