# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0002_remove_tagsnoticia_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsnoticia',
            options={'verbose_name': 'Tags de las noticia', 'verbose_name_plural': 'Tags de las noticias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='estado_noticia_email',
        ),
    ]
