# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 22:03
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0003_auto_20181210_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen_red2',
            field=image_cropping.fields.ImageRatioField('imagen', '250x143', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='imagen red2'),
        ),
    ]
