# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0004_auto_20181210_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterate',
            fields=[
                ('id_enterate', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='enterate')),
                ('imagen_red1', image_cropping.fields.ImageRatioField('imagen', '443x281', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='imagen red1')),
            ],
            options={
                'verbose_name': 'Enterate',
                'verbose_name_plural': 'Imágenes de Entérate',
                'db_table': 'enterate',
            },
        ),
    ]
