# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 00:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0006_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000),
        ),
    ]
