# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0007_auto_20181210_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informa',
            fields=[
                ('id_informa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Informate',
                'db_table': 'informa',
                'verbose_name_plural': 'Videos de Informate',
            },
        ),
    ]
