# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0008_informa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id_cabecera', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='cabecera')),
            ],
            options={
                'db_table': 'cabecera',
                'verbose_name': 'Cabecera',
                'verbose_name_plural': 'Imagenes cabecera',
            },
        ),
        migrations.AlterField(
            model_name='institucion',
            name='imagen',
            field=models.ImageField(upload_to='institucion'),
        ),
    ]
