# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0009_auto_20181211_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera',
            name='referencia',
            field=models.CharField(choices=[('1', 'index'), ('2', 'institucion'), ('3', 'noticias')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
