# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0010_cabecera_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='transparencia_ano',
            fields=[
                ('id_transparenciaano', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ano', models.CharField(max_length=50)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=700)),
            ],
            options={
                'verbose_name': 'Año de Transparencia',
                'verbose_name_plural': 'Transparencia Lista de Años',
                'db_table': 'transparencia_ano',
            },
        ),
        migrations.CreateModel(
            name='transparencia_documentos',
            fields=[
                ('id_tags', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=200)),
                ('id_transparenciaano', models.ForeignKey(db_column='id_transparenciaano', on_delete=django.db.models.deletion.DO_NOTHING, to='appeea.transparencia_ano')),
            ],
            options={
                'verbose_name': 'Transparencia Documento',
                'verbose_name_plural': 'Transparencia Documentos',
                'db_table': 'transparencia_documentos',
            },
        ),
        migrations.CreateModel(
            name='transparencia_mes',
            fields=[
                ('id_transparenciames', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mes', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mes de Transparencia',
                'verbose_name_plural': 'Tags de las noticias',
                'db_table': 'transparencia_mes',
            },
        ),
        migrations.AddField(
            model_name='transparencia_documentos',
            name='id_transparenciames',
            field=models.ForeignKey(db_column='id_transparenciames', on_delete=django.db.models.deletion.DO_NOTHING, to='appeea.transparencia_mes'),
        ),
    ]
