# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0011_auto_20181212_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparencia_ano',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=3000),
        ),
    ]
