# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0012_auto_20181212_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencia_mes',
            options={'verbose_name': 'Mes de Transparencia', 'verbose_name_plural': 'Transparencia Lista de Meses'},
        ),
        migrations.AddField(
            model_name='transparencia_documentos',
            name='subir_documento',
            field=models.FileField(default='', max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
