# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0013_auto_20181212_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEnlacesInteres',
            fields=[
                ('id_enlacesinteres', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.ImageField(upload_to='cabecera')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces de interés del index',
                'db_table': 'indexenlacesinteres',
            },
        ),
        migrations.CreateModel(
            name='IndexGeneral',
            fields=[
                ('id_indexgeneral', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces de interés del index',
                'db_table': 'indexgeneral',
            },
        ),
        migrations.CreateModel(
            name='IndexServicios',
            fields=[
                ('id_serviciosindex', models.AutoField(primary_key=True, serialize=False)),
                ('icono', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.ImageField(upload_to='cabecera')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces de interés',
                'db_table': 'indexservicios',
            },
        ),
    ]
