# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0014_indexenlacesinteres_indexgeneral_indexservicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexenlacesinteres',
            options={'verbose_name': 'Enlace', 'verbose_name_plural': 'Index Enlaces de interés'},
        ),
        migrations.AlterModelOptions(
            name='indexgeneral',
            options={'verbose_name': 'Configuración básica del sitio', 'verbose_name_plural': 'Configuración básica del sitio'},
        ),
        migrations.AlterModelOptions(
            name='indexservicios',
            options={'verbose_name': 'Servicio del index', 'verbose_name_plural': 'Index Servicios'},
        ),
        migrations.AlterField(
            model_name='indexenlacesinteres',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='indexgeneral',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
