# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0015_auto_20181218_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexenlacesinteres',
            name='url',
            field=models.ImageField(upload_to='cabecera'),
        ),
        migrations.AlterField(
            model_name='indexservicios',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
