# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0016_auto_20181218_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexenlacesinteres',
            name='imagen',
            field=models.ImageField(default='', upload_to='cabecera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexenlacesinteres',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
