# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0017_auto_20181218_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterate',
            name='publicado',
            field=models.BooleanField(default=1, verbose_name='Publicar este item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informa',
            name='publicado',
            field=models.BooleanField(default=1, verbose_name='Publicar este item'),
            preserve_default=False,
        ),
    ]
