# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0018_auto_20181218_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgeneral',
            name='flikr',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.BooleanField(verbose_name='Publicar este item'),
        ),
    ]
