# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 01:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0019_auto_20181218_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgeneral',
            name='piepagina',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=10000, verbose_name='Pie de página'),
            preserve_default=False,
        ),
    ]
