# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 03:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0020_indexgeneral_piepagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramasServicios',
            fields=[
                ('id_programasservicios', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=9999999)),
                ('fechap', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(verbose_name='Publicar este item')),
            ],
            options={
                'db_table': 'programasservicios',
            },
        ),
        migrations.AlterField(
            model_name='cabecera',
            name='referencia',
            field=models.CharField(choices=[('1', 'index'), ('2', 'institucion'), ('3', 'noticias'), ('4', 'transparencia'), ('5', 'noticia detalle'), ('6', 'detalle institución')], max_length=150),
        ),
    ]
