# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 19:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0021_auto_20181218_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
                ('descripcion', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='institucion')),
                ('imagen_red1', image_cropping.fields.ImageRatioField('imagen', '640x383', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='imagen red1')),
                ('imagen_red2', image_cropping.fields.ImageRatioField('imagen', '250x143', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='imagen red2')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('fechap', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios de la Institución',
                'db_table': 'servicios',
            },
        ),
    ]
