# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0022_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='imagen_red1',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='imagen_red2',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='imagen_red1',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='imagen_red2',
        ),
    ]
