# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 11:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0023_auto_20181220_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesosContratacionNivel1',
            fields=[
                ('id_procesos', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=9999999)),
            ],
            options={
                'verbose_name': 'Proceso Contratación Nivel 1',
                'verbose_name_plural': 'Procesos Contratación Nivel 1',
                'db_table': 'procesos1',
            },
        ),
        migrations.CreateModel(
            name='ProcesosContratacionNivel2',
            fields=[
                ('id_procesos2', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=9999999)),
                ('id_procesos', models.ForeignKey(db_column='id_procesos', on_delete=django.db.models.deletion.DO_NOTHING, to='appeea.ProcesosContratacionNivel1')),
            ],
            options={
                'verbose_name': 'Proceso Contratación Nivel 2',
                'verbose_name_plural': 'Procesos Contratación Nivel 3',
                'db_table': 'procesos2',
            },
        ),
        migrations.CreateModel(
            name='ProcesosContratacionNivel3',
            fields=[
                ('id_procesos3', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=9999999)),
                ('id_procesos2', models.ForeignKey(db_column='id_procesos2', on_delete=django.db.models.deletion.DO_NOTHING, to='appeea.ProcesosContratacionNivel2')),
            ],
            options={
                'verbose_name': 'Proceso Contratación Nivel 3',
                'verbose_name_plural': 'Procesos Contratación Nivel 3',
                'db_table': 'procesos3',
            },
        ),
    ]
