# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0024_procesoscontratacionnivel1_procesoscontratacionnivel2_procesoscontratacionnivel3'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoscontratacionnivel1',
            name='tipo',
            field=models.CharField(choices=[('1', 'menú'), ('2', 'submenú')], default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesoscontratacionnivel2',
            name='tipo',
            field=models.CharField(choices=[('1', 'menú'), ('2', 'submenú')], default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesoscontratacionnivel3',
            name='tipo',
            field=models.CharField(choices=[('1', 'menú'), ('2', 'submenú')], default='', max_length=150),
            preserve_default=False,
        ),
    ]
