# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 11:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0025_auto_20181220_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoscontratacionnivel1',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=9999999),
        ),
        migrations.AlterField(
            model_name='procesoscontratacionnivel2',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=9999999),
        ),
        migrations.AlterField(
            model_name='procesoscontratacionnivel3',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=9999999),
        ),
    ]
