# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0026_auto_20181220_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesoscontratacionnivel2',
            options={'verbose_name': 'Proceso Contratación Nivel 2', 'verbose_name_plural': 'Procesos Contratación Nivel 2'},
        ),
        migrations.AddField(
            model_name='indexservicios',
            name='estado',
            field=models.BooleanField(default='False', verbose_name='Publicar este item'),
            preserve_default=False,
        ),
    ]
