# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0027_auto_20181220_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexenlacesinteres',
            name='estado',
            field=models.BooleanField(default='True', verbose_name='Publicar este item'),
            preserve_default=False,
        ),
    ]
