# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 17:38
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0028_indexenlacesinteres_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgeneral',
            name='mapa',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
            preserve_default=False,
        ),
    ]
