# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0029_indexgeneral_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgeneral',
            name='nombre_marcador',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre d el marcador en el mapa'),
            preserve_default=False,
        ),
    ]
