# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0030_indexgeneral_nombre_marcador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgeneral',
            name='zoom',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexgeneral',
            name='nombre_marcador',
            field=models.CharField(max_length=200, verbose_name='Nombre del marcador en el mapa'),
        ),
    ]
