# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 21:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0031_auto_20181226_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_tags', models.AutoField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField()),
                ('nombre_menu', models.CharField(max_length=200, verbose_name='Nombre del Menú')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=6000)),
                ('texto_lateral', models.BooleanField()),
                ('izq_titulo', models.CharField(max_length=6000)),
                ('izq_contenido', models.CharField(max_length=6000)),
            ],
            options={
                'verbose_name': 'Nuevo menú',
                'verbose_name_plural': 'Nuevos menús',
                'db_table': 'menu_adicional',
            },
        ),
        migrations.AlterField(
            model_name='indexgeneral',
            name='zoom',
            field=models.IntegerField(verbose_name='Zoom mapa'),
        ),
    ]
