# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0032_auto_20190111_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgeneral',
            name='popup',
            field=models.ImageField(default='', upload_to='', verbose_name='Suba la imagen del popup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexgeneral',
            name='popup_habilitar',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexgeneral',
            name='popup_tiempo',
            field=models.IntegerField(default=15, verbose_name='Cerrar el popup despues de n segundos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='habilitado',
            field=models.BooleanField(verbose_name='Habilitar el Menú'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='izq_contenido',
            field=models.TextField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='menu',
            name='texto_lateral',
            field=models.BooleanField(verbose_name='Habilitar el Teto Lateral Izquierdo'),
        ),
    ]
