# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0033_auto_20190128_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencia_documentos',
            name='nro_descargas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
