# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0034_transparencia_documentos_nro_descargas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaInforma',
            fields=[
                ('id_informa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
                ('publicado', models.BooleanField(verbose_name='Publicar este item')),
            ],
            options={
                'verbose_name': 'Video de la empresa informa',
                'verbose_name_plural': 'Videos de la empresa informa',
                'db_table': 'empresainforma',
            },
        ),
        migrations.AlterField(
            model_name='indexgeneral',
            name='popup_habilitar',
            field=models.BooleanField(verbose_name='Haga clic aquí para habilitar el popup'),
        ),
    ]
