# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 00:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0035_auto_20190130_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendicionAno',
            fields=[
                ('id_rendicionano', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ano', models.CharField(max_length=50)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Rendición Año',
                'verbose_name_plural': 'Rendición de cuenta años',
                'db_table': 'rendicionano',
            },
        ),
        migrations.CreateModel(
            name='RendicionDocumentos',
            fields=[
                ('id_tags', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=200)),
                ('subir_documento', models.FileField(max_length=200, upload_to='')),
                ('nro_descargas', models.IntegerField()),
                ('id_rendicionano', models.ForeignKey(db_column='id_rendicionano', on_delete=django.db.models.deletion.DO_NOTHING, to='appeea.RendicionAno')),
            ],
            options={
                'verbose_name': 'Rendición de cuentas Documento',
                'verbose_name_plural': 'Rendición de cuentas Documentos',
                'db_table': 'rendiciondocumentos',
            },
        ),
        migrations.CreateModel(
            name='RendicionFase',
            fields=[
                ('id_rendicionfase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fase', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rendición Fase',
                'verbose_name_plural': 'Rendiciones de cuenta fases',
                'db_table': 'rendicionfase',
            },
        ),
        migrations.AddField(
            model_name='rendiciondocumentos',
            name='id_rendicionfase',
            field=models.ForeignKey(db_column='id_rendicionfase', on_delete=django.db.models.deletion.DO_NOTHING, to='appeea.RendicionFase'),
        ),
    ]
