# Generated by Django 2.2 on 2021-01-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0036_auto_20190130_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('reclamo', models.TextField(max_length=100)),
            ],
        ),
    ]
