# Generated by Django 2.2 on 2021-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0037_reclamos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendiciondocumentos',
            name='subir_documento',
            field=models.FileField(max_length=200, upload_to='media/rendicion_documentos'),
        ),
    ]
