# Generated by Django 4.2.17 on 2025-11-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeea', '0038_auto_20210327_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRegistrado',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula de Identidad')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('codigo_dactilar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Dactilar')),
                ('verificado', models.BooleanField(default=False, verbose_name='Usuario Verificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
            ],
            options={
                'verbose_name': 'Usuario Registrado',
                'verbose_name_plural': 'Usuarios Registrados',
                'db_table': 'usuario_registrado',
            },
        ),
        migrations.AlterModelOptions(
            name='reclamos',
            options={'verbose_name': 'Reclamo', 'verbose_name_plural': 'Reclamos'},
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendiciondocumentos',
            name='nombre_documento',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rendiciondocumentos',
            name='subir_documento',
            field=models.FileField(max_length=8000, upload_to='media/rendicion_documentos'),
        ),
        migrations.AlterModelTable(
            name='reclamos',
            table='reclamos',
        ),
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('login_exitoso', 'Login Exitoso'), ('login_fallido', 'Login Fallido'), ('registro', 'Registro Nuevo'), ('verificacion_email', 'Verificación Email'), ('recuperacion_password', 'Recuperación Contraseña'), ('cambio_password', 'Cambio Contraseña')], max_length=50, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='appeea.usuarioregistrado')),
            ],
            options={
                'verbose_name': 'Evento de Seguridad',
                'verbose_name_plural': 'Eventos de Seguridad',
                'db_table': 'evento_seguridad',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de Verificación')),
                ('tipo', models.CharField(choices=[('email', 'Verificación Email'), ('recuperacion', 'Recuperación Contraseña')], max_length=20, verbose_name='Tipo de Código')),
                ('usado', models.BooleanField(default=False, verbose_name='Código Usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='appeea.usuarioregistrado')),
            ],
            options={
                'verbose_name': 'Código de Verificación',
                'verbose_name_plural': 'Códigos de Verificación',
                'db_table': 'codigo_verificacion',
            },
        ),
    ]
